import { Listing } from "./types";

const img = (id: string, w = 800, h = 600) =>
  `https://picsum.photos/seed/${id}/${w}/${h}`;

const avatar = (name: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=e81111&color=fff&bold=true`;

export const listings: Listing[] = [
  {
    id: "1",
    title: "Volkswagen Golf 7 - 2018 ديزل أوتوماتيك",
    description:
      "سيارة في حالة ممتازة، صيانة دورية، إطارات جديدة، فيرنيت أصلي. أول مالك، أوراق كاملة. السعر قابل للتفاوض البسيط. للجادين فقط.",
    price: 4500000,
    category: "vehicules",
    subcategory: "voitures",
    condition: "occasion",
    conditionLabel: "مستعملة",
    wilaya: "الجزائر",
    city: "حيدرة",
    images: [img("golf7-1"), img("golf7-2"), img("golf7-3"), img("golf7-4")],
    featured: true,
    delivery: false,
    createdAt: "2025-06-08T10:30:00Z",
    views: 1340,
    seller: { name: "أمين معمري", avatar: avatar("Amine M"), type: "particulier", phone: "0550 12 34 56", memberSince: "2021", rating: 4.8, verified: true },
    attributes: [
      { label: "السنة", value: "2018" },
      { label: "الوقود", value: "ديزل" },
      { label: "علبة السرعة", value: "أوتوماتيك" },
      { label: "الكيلومتراج", value: "98 000 كلم" },
      { label: "الماركة", value: "Volkswagen" },
    ],
  },
  {
    id: "2",
    title: "شقة F4 للبيع - حي راقٍ مع كراج",
    description:
      "شقة واسعة 110م²، الطابق الثالث، مصعد، إطلالة رائعة، قريبة من جميع المرافق. عقد موثق جاهز.",
    price: 18000000,
    category: "immobilier",
    subcategory: "vente-appartement",
    wilaya: "وهران",
    city: "بئر الجير",
    images: [img("appart-1"), img("appart-2"), img("appart-3")],
    featured: true,
    createdAt: "2025-06-07T14:00:00Z",
    views: 2210,
    seller: { name: "عقارات النور", avatar: avatar("Annour"), type: "professionnel", phone: "0660 98 76 54", memberSince: "2019", rating: 4.6, verified: true },
    attributes: [
      { label: "المساحة", value: "110 م²" },
      { label: "الغرف", value: "4 غرف" },
      { label: "الطابق", value: "3" },
      { label: "الوثائق", value: "عقد موثق" },
    ],
  },
  {
    id: "3",
    title: "iPhone 15 Pro Max 256GB - جديد مختوم",
    description:
      "هاتف جديد بالكرتونة مختوم، ضمان عام، جميع الألوان متوفرة. توصيل لكل الولايات.",
    price: 320000,
    category: "telephones",
    subcategory: "smartphones",
    condition: "neuf",
    conditionLabel: "جديد",
    wilaya: "الجزائر",
    city: "باب الزوار",
    images: [img("iphone-1"), img("iphone-2"), img("iphone-3")],
    featured: true,
    delivery: true,
    createdAt: "2025-06-09T08:15:00Z",
    views: 890,
    seller: { name: "Tech Store DZ", avatar: avatar("Tech Store"), type: "professionnel", phone: "0770 11 22 33", memberSince: "2020", rating: 4.9, verified: true },
    attributes: [
      { label: "السعة", value: "256 GB" },
      { label: "الحالة", value: "جديد مختوم" },
      { label: "الضمان", value: "12 شهر" },
    ],
  },
  {
    id: "4",
    title: "MacBook Air M2 13\" - حالة الجديد",
    description:
      "لابتوب أبل M2، استعمال 3 أشهر فقط، مع العلبة والشاحن الأصلي. أداء خرافي للمونتاج والبرمجة.",
    price: 215000,
    category: "informatique",
    subcategory: "ordinateurs-portables",
    condition: "occasion",
    conditionLabel: "كالجديد",
    wilaya: "قسنطينة",
    images: [img("macbook-1"), img("macbook-2")],
    delivery: true,
    createdAt: "2025-06-06T19:45:00Z",
    views: 540,
    seller: { name: "ياسين ب.", avatar: avatar("Yacine B"), type: "particulier", phone: "0540 55 66 77", memberSince: "2022" },
    attributes: [
      { label: "المعالج", value: "Apple M2" },
      { label: "الذاكرة", value: "8 GB" },
      { label: "التخزين", value: "256 GB SSD" },
    ],
  },
  {
    id: "5",
    title: "طقم صالون مودرن 7 قطع - جلد فاخر",
    description:
      "صالون عصري بحالة ممتازة، لون رمادي أنيق، قماش عالي الجودة، مريح جداً. سبب البيع تغيير الديكور.",
    price: 95000,
    priceLabel: "قابل للتفاوض",
    category: "maison-meubles",
    subcategory: "meubles",
    condition: "occasion",
    conditionLabel: "مستعمل",
    wilaya: "سطيف",
    images: [img("salon-1"), img("salon-2")],
    createdAt: "2025-06-05T11:20:00Z",
    views: 320,
    seller: { name: "سامية ل.", avatar: avatar("Samia L"), type: "particulier", phone: "0660 33 44 55", memberSince: "2023" },
    attributes: [
      { label: "عدد القطع", value: "7" },
      { label: "المادة", value: "جلد + قماش" },
    ],
  },
  {
    id: "6",
    title: "Hyundai Tucson 2021 - بنزين فل أوبسيون",
    description:
      "سيارة عائلية SUV، حالة الوكالة، جميع الكماليات، فتحة سقف، كاميرا خلفية، شاشة كبيرة.",
    price: 6200000,
    category: "vehicules",
    subcategory: "voitures",
    condition: "occasion",
    conditionLabel: "مستعملة",
    wilaya: "البليدة",
    images: [img("tucson-1"), img("tucson-2"), img("tucson-3")],
    featured: true,
    createdAt: "2025-06-08T16:00:00Z",
    views: 1780,
    seller: { name: "كريم أوتو", avatar: avatar("Karim Auto"), type: "professionnel", phone: "0550 77 88 99", memberSince: "2018", rating: 4.7, verified: true },
    attributes: [
      { label: "السنة", value: "2021" },
      { label: "الوقود", value: "بنزين" },
      { label: "الكيلومتراج", value: "45 000 كلم" },
    ],
  },
  {
    id: "7",
    title: "مهندس برمجيات - عمل عن بعد",
    description:
      "شركة ناشئة تبحث عن مطور Full Stack بخبرة في React و Node.js. دوام كامل، راتب تنافسي، عمل عن بعد.",
    price: null,
    priceLabel: "حسب الخبرة",
    category: "emploi",
    subcategory: "offres-emploi",
    wilaya: "الجزائر",
    images: [img("job-1")],
    createdAt: "2025-06-09T09:00:00Z",
    views: 670,
    seller: { name: "Startup DZ", avatar: avatar("Startup DZ"), type: "professionnel", phone: "0770 00 11 22", memberSince: "2022", verified: true },
    attributes: [
      { label: "نوع العقد", value: "دوام كامل" },
      { label: "مكان العمل", value: "عن بعد" },
      { label: "الخبرة", value: "سنتان+" },
    ],
  },
  {
    id: "8",
    title: "PlayStation 5 + ذراعين + 3 ألعاب",
    description:
      "بلايستيشن 5 إصدار الأقراص، حالة ممتازة، مع ذراعين وألعاب FIFA و Spider-Man و GTA V.",
    price: 78000,
    category: "loisirs",
    subcategory: "jeux-video",
    condition: "occasion",
    conditionLabel: "كالجديد",
    wilaya: "عنابة",
    images: [img("ps5-1"), img("ps5-2")],
    delivery: true,
    createdAt: "2025-06-07T20:30:00Z",
    views: 1120,
    seller: { name: "رضا ق.", avatar: avatar("Reda Q"), type: "particulier", phone: "0540 22 33 44", memberSince: "2021" },
    attributes: [
      { label: "الإصدار", value: "Disc Edition" },
      { label: "الأذرع", value: "2" },
    ],
  },
  {
    id: "9",
    title: "فيلا R+2 للبيع - حي فيلات راقٍ",
    description:
      "فيلا فخمة بمساحة 250م²، 3 طوابق، حديقة، كراج لسيارتين، تشطيبات عالية الجودة.",
    price: 65000000,
    category: "immobilier",
    subcategory: "vente-villa",
    wilaya: "تيزي وزو",
    images: [img("villa-1"), img("villa-2"), img("villa-3"), img("villa-4")],
    featured: true,
    createdAt: "2025-06-04T13:00:00Z",
    views: 3050,
    seller: { name: "عقارات الأطلس", avatar: avatar("Atlas Immo"), type: "professionnel", phone: "0660 44 55 66", memberSince: "2017", rating: 4.5, verified: true },
    attributes: [
      { label: "المساحة", value: "250 م²" },
      { label: "الطوابق", value: "R+2" },
      { label: "الحديقة", value: "نعم" },
    ],
  },
  {
    id: "10",
    title: "Samsung Galaxy S24 Ultra - مستعمل نظيف",
    description:
      "هاتف سامسونج الراقي، استعمال 6 أشهر، بطارية ممتازة، مع الجراب الأصلي وحامي الشاشة.",
    price: 240000,
    priceLabel: "قابل للتفاوض",
    category: "telephones",
    subcategory: "smartphones",
    condition: "occasion",
    conditionLabel: "مستعمل",
    wilaya: "وهران",
    images: [img("s24-1"), img("s24-2")],
    delivery: true,
    createdAt: "2025-06-06T10:00:00Z",
    views: 760,
    seller: { name: "وليد ز.", avatar: avatar("Walid Z"), type: "particulier", phone: "0550 66 77 88", memberSince: "2020" },
    attributes: [
      { label: "السعة", value: "256 GB" },
      { label: "اللون", value: "أسود تيتانيوم" },
    ],
  },
  {
    id: "11",
    title: "دراجة نارية Yamaha 250cc - 2022",
    description:
      "دراجة رياضية، حالة ممتازة، كيلومتراج قليل، أوراق كاملة، صيانة منتظمة لدى الوكيل.",
    price: 850000,
    category: "vehicules",
    subcategory: "motos",
    condition: "occasion",
    conditionLabel: "مستعملة",
    wilaya: "الجزائر",
    images: [img("moto-1"), img("moto-2")],
    createdAt: "2025-06-05T17:00:00Z",
    views: 920,
    seller: { name: "نبيل م.", avatar: avatar("Nabil M"), type: "particulier", phone: "0770 33 44 55", memberSince: "2022" },
    attributes: [
      { label: "السنة", value: "2022" },
      { label: "السعة", value: "250 cc" },
    ],
  },
  {
    id: "12",
    title: "ثلاجة LG No Frost 500 لتر - جديدة",
    description:
      "ثلاجة بابين، تكنولوجيا No Frost، موفرة للطاقة A++، ضمان سنتين. توصيل وتركيب مجاني.",
    price: 145000,
    category: "maison-meubles",
    subcategory: "electromenager",
    condition: "neuf",
    conditionLabel: "جديد",
    wilaya: "قسنطينة",
    images: [img("fridge-1"), img("fridge-2")],
    delivery: true,
    featured: false,
    createdAt: "2025-06-08T12:00:00Z",
    views: 410,
    seller: { name: "Electro Plus", avatar: avatar("Electro Plus"), type: "professionnel", phone: "0660 11 22 33", memberSince: "2019", rating: 4.4, verified: true },
    attributes: [
      { label: "السعة", value: "500 لتر" },
      { label: "التقنية", value: "No Frost" },
      { label: "الفئة", value: "A++" },
    ],
  },
];
